---
title: "Cleaning Finance Tables 9A, 9D, 9E 2014-2019"
author: "Gagarin Zhao"
date: "9/0/2020"
output: github_document
---

loading knitter and packages:

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(labelled)
library(openxlsx)
```


This is when I imported and cleaned my data. I labeled the relevant variables.

## 2019 info and table 8a 9d 9e: 
```{r import and cleaning center info/table9A, 9D, 9E 2019}
uds2019centerinfo = 
  readxl::read_excel(".\\UDS2019DataDumpLA17Aug2020.xlsx", sheet = "HealthCenterInfo") %>% 
  select(HealthCenterName, BHCMISID, ReportingYear)

uds2019table8A = 
  readxl::read_excel(".\\UDS2019DataDumpLA17Aug2020.xlsx", sheet = "Table8A") %>% 
  select(-GrantNumber)

uds2019table9D = 
  readxl::read_excel(".\\UDS2019DataDumpLA17Aug2020.xlsx", sheet = "Table9D") %>% 
  select(-GrantNumber)

uds2019table9E = 
  readxl::read_excel(".\\UDS2019DataDumpLA17Aug2020.xlsx", sheet = "Table9E") %>% 
  select(-GrantNumber)

#Joined health center info, finance tables by BHCMISID:

uds2019info.t8a.t9d.t9e = full_join(uds2019centerinfo, uds2019table8A, by = "BHCMISID") %>% 
  full_join(uds2019table9D) %>%
  full_join(uds2019table9E)

```


## 2018 info and table 8a 9d 9e: 
```{r import and cleaning center info/table9A, 9D, 9E 2018}
uds2018centerinfo = 
  readxl::read_excel(".\\UDS2018DataDumpLA20Aug2019.xlsx", sheet = "HealthCenterInfo") %>% 
  select(HealthCenterName, BHCMISID, ReportingYear)

uds2018table8A = 
  readxl::read_excel(".\\UDS2018DataDumpLA20Aug2019.xlsx", sheet = "Table8A") %>% 
  select(-GrantNumber)

uds2018table9D = 
  readxl::read_excel(".\\UDS2018DataDumpLA20Aug2019.xlsx", sheet = "Table9D") %>% 
  select(-GrantNumber)

uds2018table9E = 
  readxl::read_excel(".\\UDS2018DataDumpLA20Aug2019.xlsx", sheet = "Table9E") %>% 
  select(-GrantNumber)

#Joined health center info, table 8a 9d 9e by BHCMISID:

uds2018info.t8a.t9d.t9e = full_join(uds2018centerinfo, uds2018table8A, by = "BHCMISID") %>% 
  full_join(uds2018table9D) %>% 
  full_join(uds2018table9E)

```

## 2017 info and table 8a 9d 9e: 
```{r import and cleaning center info/table9A, 9D, 9E 2017}
uds2017centerinfo = 
  readxl::read_excel(".\\UDS2017DataDumpLA14Aug2018.xlsx", sheet = "HealthCenterInfo") %>% 
  select(HealthCenterName, BHCMISID, ReportingYear)

uds2017table8A = 
  readxl::read_excel(".\\UDS2017DataDumpLA14Aug2018.xlsx", sheet = "Table8A") %>% 
  select(-GrantNumber)
uds2017table9D = 
  readxl::read_excel(".\\UDS2017DataDumpLA14Aug2018.xlsx", sheet = "Table9D") %>% 
  select(-GrantNumber)
uds2017table9E = 
  readxl::read_excel(".\\UDS2017DataDumpLA14Aug2018.xlsx", sheet = "Table9E") %>% 
  select(-GrantNumber)

#Joined health center info, table 8a 9d 9e by BHCMISID:

uds2017info.t8a.t9d.t9e = full_join(uds2017centerinfo, uds2017table8A, by = "BHCMISID") %>% 
  full_join(uds2017table9D) %>% 
  full_join(uds2017table9E)

```

## 2016 info and table 8a 9d 9e: 
```{r import and cleaning center info/table9A, 9D, 9E 2016}
uds2016centerinfo = 
  readxl::read_excel(".\\UDS2016DataDumpLA21Aug2017.xlsx", sheet = "HealthCenterInfo") %>% 
  select(HealthCenterName, BHCMISID, ReportingYear)

uds2016table8A = 
  readxl::read_excel(".\\UDS2016DataDumpLA21Aug2017.xlsx", sheet = "Table8A") %>% 
  select(-GrantNumber)

uds2016table9D = 
  readxl::read_excel(".\\UDS2016DataDumpLA21Aug2017.xlsx", sheet = "Table9D") %>% 
  select(-GrantNumber)

uds2016table9E = 
  readxl::read_excel(".\\UDS2016DataDumpLA21Aug2017.xlsx", sheet = "Table9E") %>% 
  select(-GrantNumber)

#Joined health center info, table 8a 9d 9e by BHCMISID:

uds2016info.t8a.t9d.t9e = full_join(uds2016centerinfo, uds2016table8A, by = "BHCMISID") %>% 
  full_join(uds2016table9D) %>% 
  full_join(uds2016table9E)

```

## 2015 info and table 8a 9d 9e: 
```{r import and cleaning center info/table9A, 9D, 9E 2015}
uds2015centerinfo = 
  readxl::read_excel(".\\UDS2015DataDumpLA22Aug2016.xlsx", sheet = "HealthCenterInfo") %>% 
  select(HealthCenterName, BHCMISID, ReportingYear)

uds2015table8A = 
  readxl::read_excel(".\\UDS2015DataDumpLA22Aug2016.xlsx", sheet = "Table8A") %>% 
  select(-GrantNumber)

uds2015table9D = 
  readxl::read_excel(".\\UDS2015DataDumpLA22Aug2016.xlsx", sheet = "Table9D") %>% 
  select(-GrantNumber)

uds2015table9E = 
  readxl::read_excel(".\\UDS2015DataDumpLA22Aug2016.xlsx", sheet = "Table9E") %>% 
  select(-GrantNumber)

#Joined health center info, table 8a 9d 9e by BHCMISID:

uds2015info.t8a.t9d.t9e = full_join(uds2015centerinfo, uds2015table8A, by = "BHCMISID") %>% 
  full_join(uds2015table9D) %>% 
  full_join(uds2015table9E)

```


## 2014 info and table 8a 9d 9e: 
```{r import and cleaning center info/table9A, 9D, 9E 2014}
uds2014centerinfo = 
  readxl::read_excel(".\\UDS2014DataDumpLA31Jul2015.xlsx", sheet = "HealthCenterInfo") %>% 
  select(HealthCenterName, BHCMISID, ReportingYear)

uds2014table8A = 
  readxl::read_excel(".\\UDS2014DataDumpLA31Jul2015.xlsx", sheet = "Table8A") %>% 
  select(-GrantNumber)

uds2014table9D = 
  readxl::read_excel(".\\UDS2014DataDumpLA31Jul2015.xlsx", sheet = "Table9D") %>% 
  select(-GrantNumber)

uds2014table9E = 
  readxl::read_excel(".\\UDS2014DataDumpLA31Jul2015.xlsx", sheet = "Table9E") %>% 
  select(-GrantNumber)

#Joined health center info, table 8a 9d 9e by BHCMISID:

uds2014info.t8a.t9d.t9e = full_join(uds2014centerinfo, uds2014table8A, by = "BHCMISID") %>% 
  full_join(uds2014table9D) %>% 
  full_join(uds2014table9E)

```

